routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');

Route::get('{provider}/auth','SocialController@auth')->name('social.auth');

Route::get('{provider}/redirect','SocialController@auth_callback')->name('social.authcallback');

Route::resource('channels','ChannelController')->middleware('auth');

Route::resource('discussions','DiscussionController')->middleware('auth');

Route::post('/discussions/reply/{id}','DiscussionController@reply')->middleware('auth');



Route::get('/likes/like/{id}','LikeController@like')->middleware('auth');

Route::get('/likes/unlike/{id}','LikeController@unlike')->middleware('auth');

Route::get('/channel/{slug}','ForumController@channel')->middleware('auth');

Route::get('/watch/{id}','WatcherController@watch')->middleware('auth');

Route::get('/unwatch/{id}','WatcherController@unwatch')->middleware('auth');

Route::get('/reply/bestanswer/{id}','DiscussionController@markbestanswer')->middleware('auth');

resources/views/channel.blade.php
@extends('layouts.app')

@section('content')

                <h1 class="text-center">{{$namos}}</h1>

            @foreach($discussions as $onediscussion)
            <div class="card">
                <div class="card-header">

                    <img src="{{$onediscussion->user->avatar}}" alt="" height="40px" width="40px" style="border-radius:  50%;">&nbsp;&nbsp;&nbsp;
                    <span>{{$onediscussion->user->name}}&nbsp;({{$onediscussion->user->experience}} Pts)&nbsp;&nbsp;<b>created: {{$onediscussion->created_at->diffForHumans()}}</b></span>
                    @if($onediscussion->hasbestanswer() != 1)  <button type="button" class="btn btn-outline-success btn-sm" style="float: right;">Open</button> @else <button class="btn btn-outline-danger btn-sm" style="float:right;">Closed</button>  @endif  
                    <a href="/discussions/{{$onediscussion->slug}}" class ="btn btn-info btn-sm" style="float: right;">view</a>

                </div>

                <div class="card-body">
                <h4 class="text-center">{{$onediscussion->title}}</h4>
                  <p class="text-center">{{str_limit($onediscussion->content,100)}}</p>  

                </div>
                <div class="card-footer"> <?php $a = $onediscussion->replies->count() ; ?>  @if($a==1){{$a}} reply @else {{$a}} replies @endif  <button class="btn btn-warning btn-sm" style="float:right;"> {{$onediscussion->channel->title}} </button></div>
            </div><br>@endforeach
            <div class="text-center">{{$discussions->links()}}</div>
            

@endsection

resources/views/discuss.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
          @if($errors->any())
            <div class="alert alert-danger" role="alert">
                <ul>
                    
                    @foreach($errors->all() as $error)
                        <li> {{$error}}</li>
                    @endforeach

                </ul>
              
            </div>
            @endif
            <div class="card">
                <div class="card-header">Create A Discussion</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{route('discussions.store')}}" method="post">
                        @csrf
                        
                      <div class="form-group">
                          
                            <select name="channel_id" id="channel_id">
                              
                                  @foreach($channels as $channel)
                                  <option value="{{$channel->id}}">{{$channel->title}}</option>
                                  @endforeach
                            </select>

                      </div>

                      <div class="form-group">
                        
                        <input type="text" name ="title" placeholder="Entrer un titre">

                      </div>


                      <div class="form-group">
                        
                        <textarea name="content" id="content" cols="50" rows="10">ask a question</textarea>

                      </div>

                      <div class="form-group">
                          

                          <button class="btn-success" type='submit'>Add A DISCUSSION</button>
                      </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/forum.blade.php
@extends('layouts.app')

@section('content')

            @foreach($thediscussions as $onediscussion)
            <div class="card">
                <div class="card-header">

                    <img src="{{$onediscussion->user->avatar}}" alt="" height="40px" width="40px" >&nbsp;&nbsp;&nbsp;
                    <span>{{$onediscussion->user->name}}&nbsp;&nbsp;&nbsp;<b>created: {{$onediscussion->created_at->diffForHumans()}}</b></span>
                    @if($onediscussion->hasbestanswer() != 1)  <button type="button" class="btn btn-outline-success btn-sm" style="float: right;">Open</button> @else <button class="btn btn-outline-danger btn-sm" style="float:right;">Closed</button>  @endif  
                    <a href="discussions/{{$onediscussion->slug}}" class ="btn btn-info btn-sm" style="float: right;">view</a>

                </div>

                <div class="card-body">
                <h4 class="text-center">{{$onediscussion->title}}</h4>
                  <p class="text-center">{{str_limit($onediscussion->content,100)}}</p>  

                </div>
                <div class="card-footer"> <?php $a = $onediscussion->replies->count() ; ?>  @if($a==1){{$a}} reply @else {{$a}} replies @endif  <a href="/channel/{{$onediscussion->channel->slug}}" class="btn btn-warning btn-sm" style="float:right;"> {{$onediscussion->channel->title}}</a></div>
            </div><br>@endforeach
            <div class="text-center">{{$thediscussions->links()}}</div>
            

@endsection