routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');

Route::get('{provider}/auth','SocialController@auth')->name('social.auth');

Route::get('{provider}/redirect','SocialController@auth_callback')->name('social.authcallback');

Route::resource('channels','ChannelController')->middleware('auth');

Route::resource('discussions','DiscussionController')->middleware('auth');

Route::post('/discussions/reply/{id}','DiscussionController@reply')->middleware('auth');



Route::get('/likes/like/{id}','LikeController@like')->middleware('auth');

Route::get('/likes/unlike/{id}','LikeController@unlike')->middleware('auth');

Route::get('/channel/{slug}','ForumController@channel')->middleware('auth');

Route::get('/watch/{id}','WatcherController@watch')->middleware('auth');

Route::get('/unwatch/{id}','WatcherController@unwatch')->middleware('auth');

Route::get('/reply/bestanswer/{id}','DiscussionController@markbestanswer')->middleware('auth');

app/Channel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Channel extends Model
{
   public function user(){

   	$this->belongsTo('App\User');
   }

   public function discussions(){

   	return $this->hasMany('App\Discussion');
   }
}

app/Http/Controllers/ChannelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Channel;
use Session;

class ChannelController extends Controller
{



    public function __construct(){

            $this->middleware('admin');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /*$channels = DB::table('channels')->get();*/

        /*dd($channels);*/

        /*on les a envoyer golbalement*/



        return view('channels.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('channels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([

                'title'=>'required'

        ]);
        
        $newchannel = new Channel;
        $newchannel->title = $request->title;
        $newchannel->slug = str_slug($request->title);

        $newchannel->save();

        Session::flash('success','new channel created');

        return redirect('channels');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $channels= DB::table('channels')->where('id','=',$id)->first();

        

        return view('channels.edit')->with('channel',$channels);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $channeltoedit = Channel::find($id);

        $channeltoedit->title = $request->title;
        $channeltoedit->slug = str_slug($request->title);
        $channeltoedit->save();

        return redirect('channels');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       
       $channel = DB::table('channels')->where('id','=',$id);

       
        $channel->delete();

        return redirect()->back();

    }
}

resources/views/channels/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create A Channel</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form action="{{route('channels.store')}}" method="post">
                        @csrf
                        
                      <div class="form-group">
                          
                            <input type="text" name="title" class="form-control">

                      </div>

                      <div class="form-group">
                          

                          <button class="btn-success" type='submit'>Add channel</button>
                      </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/channels/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit A Channel</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif



                    <form action="/channels/{{$channel->id}}" method="post">
                      @method('PUT')
                        @csrf
                        
                      <div class="form-group">
                          
                            <input type="text" name="title" class="form-control" value="{{$channel->title}}">

                      </div>

                      <div class="form-group">
                          

                          <button class="btn-success" type='submit'>Update channel</button>
                      </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/channels/index.blade.php
@extends('layouts.app')

@section('content')

            <div class="card">
                <div class="card-header">Channels</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table table-striped">
                        <thead>
                        <tr><th> Channel</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr></thead>
                    @if(!$channels->isEmpty())
                    @foreach($channels as $channel)
                    <tr>
                        
                        <td>{{$channel->title}} </td>
                        <td><a href="{{route('channels.edit',['channel'=>$channel->id])}}" class="btn btn-info">Edit</a> </td>
                        <td><form action="{{route('channels.destroy',['channel'=>$channel->id])}}" method="post">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-xs btn-danger" type="submit"> Delete</button>

                        </form>

                             </td>
                        
                    </tr>

                     @endforeach
                     @endif   
                    </table>
                </div>
            </div>

@endsection