routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/forum', 'ForumController@index')->name('forum');

Route::get('{provider}/auth','SocialController@auth')->name('social.auth');

Route::get('{provider}/redirect','SocialController@auth_callback')->name('social.authcallback');

Route::resource('channels','ChannelController')->middleware('auth');

Route::resource('discussions','DiscussionController')->middleware('auth');

Route::post('/discussions/reply/{id}','DiscussionController@reply')->middleware('auth');



Route::get('/likes/like/{id}','LikeController@like')->middleware('auth');

Route::get('/likes/unlike/{id}','LikeController@unlike')->middleware('auth');

Route::get('/channel/{slug}','ForumController@channel')->middleware('auth');

Route::get('/watch/{id}','WatcherController@watch')->middleware('auth');

Route::get('/unwatch/{id}','WatcherController@unwatch')->middleware('auth');

Route::get('/reply/bestanswer/{id}','DiscussionController@markbestanswer')->middleware('auth');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/forum') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">Login</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">

            <div class="container">
                <div class="row">
                    <div class="col-4">

                        <div class="card">
                            <a href="{{route('discussions.create')}}" class= "btn btn-info">create a Discussion</a> <br>
                         <div class="card-header">Menu</div>

                         <div class="card-body">

                            <ul>
                                <li class="list-group-item">
                                    
                                    <a href="/forum">Home</a>
                                </li>
                                @if(@auth::check())
                                    @if(Auth::user()->admin)
                                <li class="list-group-item">
                                    
                                    <a href="/channels">Channels</a>
                                </li>

                                <li class="list-group-item">
                                    
                                    <a href="/channels/create">Create Channel</a>
                                </li>
                                @endif
                                @endif

                                <li class="list-group-item">
                                    
                                    <a href="/forum?filter=me"> My Discussions</a>
                                </li>

                                <li class="list-group-item">
                                    
                                    <a href="/forum?filter=solved"> Solved Discussions</a>
                                </li>
                            </ul>

                            <ul><h4 class="text-center">Channels</h4> 
                            @foreach($channels as $channel)
                            <li class="list-group-item"><a href="/channel/{{$channel->slug}}">{{$channel->title}}</a></li>
                            @endforeach
                        </ul></div></div> </div>
                     <div class="col-8"> @yield('content')</div></div>
                
            </div>
           
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
</body>
</html>